# Generated by Django 3.1.7 on 2021-04-03 08:27

from django.db import migrations, models
import qlns.apps.core.models.employee


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.svg', upload_to=qlns.apps.core.models.employee.upload_to),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Seperated', 'Seperated'), ('Widowed', 'Widowed'), ('Other', 'Other')], max_length=10),
        ),
    ]
