# Generated by Django 3.1.7 on 2021-04-09 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_educationlevel_language_license_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.license')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='core.employee')),
            ],
        ),
    ]
