# Generated by Django 3.1.7 on 2021-04-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employeelanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('GPA', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.educationlevel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='core.employee')),
            ],
        ),
    ]
