# Generated by Django 3.1.7 on 2021-05-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_applicationconfig_monthly_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationconfig',
            name='time_zone',
        ),
    ]
