# Generated by Django 3.1.7 on 2021-05-08 05:13

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_remove_applicationconfig_time_zone'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM qlns.core_applicationconfig"),
        migrations.RunSQL([
            ("INSERT INTO core_applicationconfig (monthly_start_date) VALUES(%s);", [1])
        ])
    ]
