# Generated by Django 3.1.7 on 2021-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_seed_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfig',
            name='ot_point_rate',
            field=models.FloatField(default=1.5),
        ),
    ]
