# Generated by Django 3.1.7 on 2021-05-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_applicationconfig_ot_point_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfig',
            name='early_check_in_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
