# Generated by Django 3.1.7 on 2021-05-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_termination_models'),
        ('core', '0021_applicationconfig_early_check_in_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.job'),
        ),
    ]
