# Generated by Django 3.1.7 on 2021-05-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_employee_current_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'default_permissions': ('add', 'change', 'view'), 'permissions': (('can_set_role_employee', 'Can change employee role'), ('can_set_password_employee', 'Can change employee password'))},
        ),
    ]
