# Generated by Django 3.1.7 on 2021-06-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_employee_action_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfig',
            name='require_face_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_model_path',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
