# Generated by Django 3.1.7 on 2021-06-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_change_avatar_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfig',
            name='allow_unrecognised_face',
            field=models.BooleanField(default=False),
        ),
    ]
