# Generated by Django 3.1.7 on 2021-04-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20210418_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='is_ot',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Confirmed', 'Confirmed')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='check_in_note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='check_out_note',
            field=models.TextField(null=True),
        ),
    ]
