# Generated by Django 3.1.7 on 2021-04-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employeeskill'),
        ('attendance', '0004_auto_20210418_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.employee'),
        ),
    ]
