# Generated by Django 3.1.7 on 2021-04-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_update_location_geo'),
        ('attendance', '0005_auto_20210418_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.location'),
        ),
    ]
