# Generated by Django 3.1.7 on 2021-04-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_tracking_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='actual_hours_modification_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='actual_hours_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ot_hours_modification_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ot_hours_modified',
            field=models.BooleanField(default=False),
        ),
    ]
