# Generated by Django 3.1.7 on 2021-04-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_paid', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
