# Generated by Django 3.1.7 on 2021-04-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employeeskill'),
        ('attendance', '0009_timeofftype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TimeOff', to='core.employee')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ReviewedTimeOff', to='core.employee')),
                ('time_off_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TimeOff', to='attendance.timeofftype')),
            ],
        ),
    ]
