# Generated by Django 3.1.7 on 2021-04-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_schedule_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoff',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='attendance.schedule'),
            preserve_default=False,
        ),
    ]
