# Generated by Django 3.1.7 on 2021-04-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_timeoff_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='attendance.schedule'),
            preserve_default=False,
        ),
    ]
