# Generated by Django 3.1.7 on 2021-04-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_timeoff_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='work_hours',
            field=models.FloatField(default=0),
        ),
    ]
