# Generated by Django 3.1.7 on 2021-05-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_holiday_work_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='overtime_type',
        ),
        migrations.AddField(
            model_name='tracking',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OvertimeType',
        ),
    ]
