# Generated by Django 3.1.7 on 2021-05-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_remove_overtime_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='work_hours',
        ),
    ]
