# Generated by Django 3.1.7 on 2021-05-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_remove_holiday_work_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_zone',
        ),
    ]
