# Generated by Django 3.1.7 on 2021-05-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_remove_schedule_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='actual_work_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tracking',
            name='ot_work_hours',
            field=models.FloatField(default=0),
        ),
    ]
