# Generated by Django 3.1.7 on 2021-05-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_tracking_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
