# Generated by Django 3.1.7 on 2021-05-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_remove_attendance_confirmed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Confirmed', 'Confirmed')], default='Pending', max_length=15),
        ),
    ]
