# Generated by Django 3.1.7 on 2021-05-08 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_clear_attendance_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='attendance.period'),
            preserve_default=False,
        ),
    ]
