# Generated by Django 3.1.7 on 2021-05-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'default_permissions': ('view',), 'permissions': (('can_revert_attendance', 'Can revert employee attendance'), ('can_reject_attendance', 'Can reject employee attendance'), ('can_approve_attendance', 'Can approve employee attendance'), ('can_confirm_attendance', 'Can confirm employee attendance'), ('can_edit_actual_hours_attendance', 'Can edit actual hours of an employee attendance'), ('can_edit_overtime_hours_attendance', 'Can edit overtime hours of an employee attendance'))},
        ),
    ]
