# Generated by Django 3.1.7 on 2021-05-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_attendance_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeoff',
            options={'default_permissions': ('view',), 'permissions': (('can_reject_timeoff', 'Can reject time off'), ('can_approve_timeoff', 'Can approve time off'))},
        ),
    ]
