# Generated by Django 3.1.7 on 2021-05-31 15:18

from django.db import migrations, models
import qlns.apps.attendance.models.tracking


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_time_off_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='face_authorized',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='image',
            field=models.ImageField(null=True, upload_to=qlns.apps.attendance.models.tracking.upload_to),
        ),
    ]
