# Generated by Django 3.1.7 on 2021-06-01 08:23

from django.db import migrations, models
import qlns.apps.attendance.models.tracking


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_add_face_image_to_tracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='image',
            new_name='check_in_image',
        ),
        migrations.AddField(
            model_name='tracking',
            name='check_out_image',
            field=models.ImageField(null=True, upload_to=qlns.apps.attendance.models.tracking.upload_to),
        ),
    ]
