# Generated by Django 3.1.7 on 2021-06-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_check_out_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='face_authorized',
            new_name='check_in_face_authorized',
        ),
        migrations.AddField(
            model_name='tracking',
            name='check_out_face_authorized',
            field=models.BooleanField(null=True),
        ),
    ]
