# Generated by Django 3.1.7 on 2021-07-18 05:38

from django.db import migrations, models
import django.db.models.deletion
import qlns.apps.attendance.models.employee_face


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_employee_face_model_path'),
        ('attendance', '0030_tracking_check_out_face_authorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azure_face_id', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=qlns.apps.attendance.models.employee_face.upload_to)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Faces', to='core.employee')),
            ],
            options={
                'default_permissions': ('view', 'add', 'delete'),
            },
        ),
    ]
