version: "3.9"
   
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_DB=qlns
      - MYSQL_USER=root
      - MYSQL_PASSWORD=LLV6#s9ustmIp7xz
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
