# Generated by Django 3.1.7 on 2021-05-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('base_on', models.CharField(choices=[('Basic Salary', 'Basicsalary'), ('Gross Salary', 'Grosssalary')], max_length=100)),
                ('percent_company', models.FloatField()),
                ('percent_employee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('tax_type', models.CharField(choices=[('Progressive', 'Progressive'), ('FixedPercentage', 'Fixedpercentage')], max_length=100)),
            ],
        ),
    ]
