# Generated by Django 3.1.7 on 2021-05-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employeesalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_check_in', models.BooleanField()),
                ('monthly_start_date', models.IntegerField()),
            ],
        ),
    ]
