# Generated by Django 3.1.7 on 2021-05-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_salarysystemfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cycle_start_date', models.DateTimeField()),
                ('cycle_end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('templates', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.salarytemplate')),
            ],
        ),
    ]
