# Generated by Django 3.1.7 on 2021-05-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dependent'),
        ('payroll', '0007_employee_has_one_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='core.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('readonly_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarytemplatefield')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='payroll.payslip')),
            ],
        ),
    ]
