# Generated by Django 3.1.7 on 2021-05-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payslip_payslipvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
