# Generated by Django 3.1.7 on 2021-05-08 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0009_employeesalary_basic_salary'),
    ]

    query = "INSERT INTO payroll_salarysystemfield (name, code_name, description) VALUES(%s, %s, %s);"

    operations = [
        migrations.RunSQL(
            sql=[
                "DELETE FROM qlns.payroll_salarysystemfield",
                (query, ["ID", "id", "Mã nhân viên"]),
                (query, ["Tên", "first_name", None]),
                (query, ["Họ", "last_name", None]),
                (query, ["Họ và tên", "full_name", None]),
                (query, ["Email", "email", None]),
                (query, ["Giới tính", "gender", None]),
                (query, ["Ngày sinh", "birthday", None]),
                (query, ["Số điện thoại", "phone", None]),
                (query, ["Quốc tịch", "nationality", None]),
                (query, ["Mã số thuế", "personal_tax_id", None]),
                (query, ["Mã số bảo hiểm xã hội", "social_insurance", None]),
                (query, ["Mã số bảo hiểm y tế", "health_insurance", None]),

                (query, ["Tên ngân hàng", "bank_name", None]),
                (query, ["Chi nhánh", "bank_branch", None]),
                (query, ["Chủ tài khoản", "bank_account_holder", None]),
                (query, ["Số tài khoản", "bank_account_number", None]),

                (query, ["Chức vụ công việc", "job_title", None]),
                (query, ["Phòng ban", "department", None]),
                (query, ["Vị trí công tác", "location", None]),
                (query, ["Trạng thái tuyển dụng", "employment_status", None]),
                (query, ["Ngày bắt đầu thử việc", "probation_start_date", None]),
                (query, ["Ngày kết thúc thử việc", "probation_end_date", None]),
                (query, ["Ngày hợp đồng có hiệu lực", "contract_start_date", None]),
                (query, ["Ngày kết thúc hợp đồng", "contract_end_date", None]),

                # Salary info
                (query, ["Mức lương thực tế", "salary", None]),
                (query, ["Mức lương cơ bản", "basic_salary", None]),
                (query, ["Tên chế độ thuế", "tax_plan_name", None]),
                (query, ["Mã chế độ thuế", "tax_plan_code", None]),
                (query, ["Tên chế độ bảo hiểm", "insurance_plan_name", None]),
                (query, ["Mã chế độ bảo hiểm", "insurance_plan_code", None]),
                (query, ["Số người phụ thuộc", "number_of_dependants", None]),

                # Working data
                (query, ["Công chuẩn", "schedule_work_point", "Số ngày công chuẩn"]),
                (query, ["Công thực tế", "actual_work_point",
                         "Số ngày công thực tế (bao gồm cả công nhận được do nghỉ phép, nghỉ lễ, làm ngoài giờ)"]),
                (query, ["Công hành chính", "normal_work_point", "Số công làm hành chính"]),
                (query, ["Công ngoài giờ", "overtime_work_point", "Số công làm ngoài giờ"]),
                (query, ["Công nghỉ phép", "paid_time_off_point", "Số công được nhận khi nghỉ phép có tính lương"]),
                (query, ["Công nghỉ lễ", "holiday_point", "Số công được nhận do nghỉ lễ"]),

            ],
            reverse_sql=[
                "DELETE FROM qlns.payroll_salarysystemfield"
            ]
        )
    ]
