# Generated by Django 3.1.7 on 2021-05-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_seed_system_fields'),
    ]

    operations = [
        migrations.RunSQL(
            sql=["DELETE FROM qlns.payroll_payslipvalue;"],
        ),
        migrations.RunSQL(
            sql=["DELETE FROM qlns.payroll_payslip;"],
        ),
        migrations.RunSQL(
            sql=["DELETE FROM qlns.payroll_payroll;"],
        )
    ]
