# Generated by Django 3.1.7 on 2021-05-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_period'),
        ('payroll', '0011_clear_payroll_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='cycle_end_date',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='cycle_start_date',
        ),
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='attendance.period'),
            preserve_default=False,
        ),
    ]
