# Generated by Django 3.1.7 on 2021-05-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_payroll_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslipvalue',
            name='readonly_value',
        ),
        migrations.RemoveField(
            model_name='payslipvalue',
            name='value',
        ),
        migrations.AddField(
            model_name='payslipvalue',
            name='num_value',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='payslipvalue',
            name='str_value',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
