# Generated by Django 3.1.7 on 2021-05-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_payroll_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='payroll.salarytemplate'),
        ),
    ]
