# Generated by Django 3.1.7 on 2021-05-17 06:36

from django.db import migrations


def create_default_policies(apps, schema_editor):
    TaxPolicy = apps.get_model('payroll', 'TaxPolicy')
    default_tax_policy = TaxPolicy.objects.filter(code='vn_progessive').first()
    if default_tax_policy is None:
        default_tax_policy = TaxPolicy(name='VN Progressive', code='vn_progessive', tax_type='Progressive')
        default_tax_policy.save()

    InsurancePolicy = apps.get_model('payroll', 'InsurancePolicy')
    default_insurance_policy = InsurancePolicy.objects.filter(code='vn_standard').first()
    if default_insurance_policy is None:
        default_insurance_policy = InsurancePolicy(
            name="VN Standard",
            code="vn_standard",
            base_on="Basic Salary",
            percent_company=21.5,
            percent_employee=10.5
        )
        default_insurance_policy.save()


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0015_templated_related_name'),
    ]

    operations = [
        migrations.RunPython(create_default_policies)
    ]
