# Generated by Django 3.1.7 on 2021-05-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_salarytemplatefield_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarysystemfield',
            name='datatype',
            field=models.CharField(choices=[('Number', 'Number'), ('Currency', 'Currency'), ('Text', 'Text')], default='Text', max_length=20),
            preserve_default=False,
        ),
    ]
