# Generated by Django 3.1.7 on 2021-05-19 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0018_salarysystemfield_datatype'),
    ]

    operations = [
        migrations.RunSQL("UPDATE payroll_salarysystemfield SET datatype = 'Currency' WHERE code_name ='salary';"),
        migrations.RunSQL(
            "UPDATE payroll_salarysystemfield SET datatype = 'Currency' WHERE code_name ='basic_salary';"),
        migrations.RunSQL("UPDATE payroll_salarysystemfield SET datatype = 'Number' WHERE code_name "
                          "='number_of_dependants';"),
        migrations.RunSQL("UPDATE payroll_salarysystemfield SET datatype = 'Number' WHERE code_name "
                          "='schedule_work_point';"),
        migrations.RunSQL(
            "UPDATE payroll_salarysystemfield SET datatype = 'Number' WHERE code_name ='actual_work_point';"),
        migrations.RunSQL(
            "UPDATE payroll_salarysystemfield SET datatype = 'Number' WHERE code_name ='normal_work_point';"),
        migrations.RunSQL(
            "UPDATE payroll_salarysystemfield SET datatype = 'Number' WHERE code_name ='overtime_work_point';"),
        migrations.RunSQL("UPDATE payroll_salarysystemfield SET datatype = 'Number' WHERE code_name "
                          "='paid_time_off_point';"),
        migrations.RunSQL("UPDATE payroll_salarysystemfield SET datatype = 'Number' WHERE code_name ='holiday_point';"),
        migrations.RunSQL("UPDATE payroll_salarysystemfield SET datatype = 'Number' WHERE code_name ='sum_late';"),
    ]
