# Generated by Django 3.1.7 on 2021-05-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_payroll_confirmed_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'default_permissions': ('view', 'delete', 'add'), 'permissions': (('can_calculate_payroll', 'Can calculate payroll'), ('can_export_excel_payroll', 'Can export payroll to excel file'), ('can_send_payslip_payroll', 'Can send payslip'), ('can_confirm_payroll', 'Can confirm payroll'))},
        ),
    ]
