# Generated by Django 3.1.7 on 2021-05-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_payroll_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'default_permissions': ('view',)},
        ),
        migrations.AlterModelOptions(
            name='payslipvalue',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='salarytemplatefield',
            options={'default_permissions': ()},
        ),
    ]
