# Generated by Django 3.1.7 on 2021-05-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_change_default_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarysystemfield',
            options={'default_permissions': ('change',)},
        ),
    ]
