# Generated by Django 3.1.7 on 2021-06-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_change_default_system_field_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarytemplate',
            name='is_default',
        ),
    ]
