# Generated by Django 3.1.7 on 2021-06-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_remove_salarytemplate_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytemplatefield',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
