# Generated by Django 3.1.7 on 2021-06-21 15:24

from django.db import migrations, models
import qlns.apps.payroll.models.payroll


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_salarytemplatefield_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='input_file',
            field=models.FileField(null=True, upload_to=qlns.apps.payroll.models.payroll.upload_to),
        ),
        migrations.AlterField(
            model_name='salarytemplatefield',
            name='type',
            field=models.CharField(choices=[('System Field', 'Systemfield'), ('Formula', 'Formula'), ('Input', 'Input')], max_length=50),
        ),
    ]
