from .DjangoModelPermissionOrIsOwner import DjangoModelPermissionOrIsOwner
from .RWPermissionOrIsOwner import RWPermissionOrIsOwner
from .RWPermissionOrViewOwn import RWPermissionOrViewOwn
from .RWPermissionOrReadonly import RWPermissionOrReadOnly
