# Generated by Django 3.1.7 on 2021-04-07 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_unique_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),

        migrations.RunSQL([("INSERT INTO job_employmentstatus (name) VALUES (%s);", ['Onboarding'])]),
        migrations.RunSQL([("INSERT INTO job_employmentstatus (name) VALUES (%s);", ['Probationary'])]),
        migrations.RunSQL([("INSERT INTO job_employmentstatus (name) VALUES (%s);", ['Active'])]),
        migrations.RunSQL([("INSERT INTO job_employmentstatus (name) VALUES (%s);", ['On Leave'])]),

        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),

        migrations.RunSQL([("INSERT INTO job_jobevent (name) VALUES (%s);", ['Error Correction'])]),
        migrations.RunSQL([("INSERT INTO job_jobevent (name) VALUES (%s);", ['Joined'])]),
        migrations.RunSQL([("INSERT INTO job_jobevent (name) VALUES (%s);", ['Location Changed'])]),
        migrations.RunSQL([("INSERT INTO job_jobevent (name) VALUES (%s);", ['Promoted'])]),
        migrations.RunSQL([("INSERT INTO job_jobevent (name) VALUES (%s);", ['Other'])]),

        migrations.AddField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='job.jobtitle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='job.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='job.jobevent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.employmentstatus'),
        ),
    ]
