# Generated by Django 3.1.7 on 2021-04-07 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_unique_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='event',
            field=models.CharField(choices=[('Error Correction', 'Error Correction'), ('Joined', 'Joined'), ('Location Changed', 'Location Changed'), ('Promoted', 'Promoted'), ('Other', 'Other')], default='Joined', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
