# Generated by Django 3.1.7 on 2021-04-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_modify_job_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='work_shift',
        ),
        migrations.DeleteModel(
            name='WorkShift',
        ),
    ]
