# Generated by Django 3.1.7 on 2021-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='accurate_address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='location',
            name='allow_outside',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='radius',
            field=models.FloatField(default=100),
        ),
    ]
