# Generated by Django 3.1.7 on 2021-05-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_update_location_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='termination_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='termination_note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='termination_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
