# Generated by Django 3.1.7 on 2021-05-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_termination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='event',
        ),
        migrations.AddField(
            model_name='job',
            name='event',
            field=models.CharField(choices=[('Error Correction', 'Error Correction'), ('Joined', 'Joined'), ('Location Changed', 'Location Changed'), ('Other', 'Other'), ('Promoted', 'Promoted'), ('Terminated', 'Terminated')], default='Joined', max_length=100),
        ),
    ]
