# Generated by Django 3.1.7 on 2021-05-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_delete_jobevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_terminated',
        ),
        migrations.RemoveField(
            model_name='job',
            name='termination_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='termination_note',
        ),
        migrations.RemoveField(
            model_name='job',
            name='termination_reason',
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termination', to='job.job')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termination', to='job.terminationreason')),
            ],
        ),
    ]
