# Generated by Django 3.1.7 on 2021-05-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_current_job_data_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'default_permissions': ('add', 'delete', 'view'), 'permissions': (('can_terminate_job', 'Can terminate employment'),)},
        ),
    ]
